[package]
name = "bitcoin-harness"
version = "0.1.0"
authors = ["CoBloX Team <team@coblox.tech>"]
edition = "2018"

[dependencies]
base64 = "0.12.3"
bitcoin = { version = "0.23", features = ["use-serde"] }
bitcoincore-rpc = "0.11.0"
futures = "0.3.5"
hex = "0.4.2"
serde_json = "1"
testcontainers = "0.9"
thiserror = "1.0"
tokio = { version = "0.2", default-features = false, features = ["blocking", "macros", "rt-core", "time"] }
tracing = "0.1"
url = "2"
